---
title: "Semi-Markov models with msmbayes"
author: "Christopher Jackson <chris.jackson@mrc-bsu.cam.ac.uk>"
date: "`r Sys.Date()`"
output: 
  rmarkdown::html_document:
    toc: true
    toc_float: true
    theme: simplex
    number-sections: true
resource_files:
  - ../man/figures/twostate.png
vignette: >
  %\VignetteIndexEntry{Semi-Markov models with msmbayes}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

Non-Markov models have traditionally been difficult for intermittently observed data, since we do not know the times of entry to the states. For some transition structures, we may not even know whether or not any particular transition took place within an interval between observations.  Hence it can be hard to discern how the hazard of transition out of a state depends on the time spent in that state.

`msmbayes` can fit multi-state models where the sojourn distribution in any state has a special two-parameter distribution.   This relaxes the Markov assumption, producing a semi-Markov model, where the transition rate out of a state depends on how long the individual has spent in the state.   The sojourn distribution used for these models is a _phase-type approximation to a shape-scale distribution_, introduced by [Titman, 2014](https://doi.org/10.1007/s11222-012-9360-6).


## Phase-type shape-scale distributions

The distribution has two parameters: shape $a$ and scale $b$.  The probability distribution function is defined by 

\[ F(x | a, b) = F_p(x | \lambda  = b*h(a)) \]

where $F_p(x | \lambda)$ is a phase-type distribution with 5 phases and transition rates $\lambda$.   The shape and scale are mapped to the phase-type transition rates through a function $h()$, determined so that the phase-type distribution approximates either a Weibull or a Gamma over a wide range of shape parameters.  This function is pre-determined and stored in the `msmbayes` package.

The full procedure used to determine $h()$ is [documented] - essentially the Kullback-Leibler discrepancy between the phase-type distribution and the Weibull is minimised for a series of points on a fine grid between [min,max]. and interpolated using a Hermite cubic spline, and extended beyond the boundaries with a constant to define a full time-to-event distribution function for positive times x.  Done for shape = 1, then re-scaled 

* Covariates are applied to the scale parameter $b$, in the typical fashion as a linear model on $log(b)$. 

* When this model is used as a sojourn distribution in some state $r$, additional assumptions are needed if there are multiple alternative states $s$ that an individual can transition to immediately on leaving $r$.   In `msmbayes`, this transition is governed by a constant transition probability $\pi_{rs}$, as is done in [Titman, 2014](https://doi.org/10.1007/s11222-012-9360-6). This assumes that the transition probability does not depend on the length of time spent in state $r$ --- the supplementary material to [Titman, 2014](https://doi.org/10.1007/s11222-012-9360-6) discusses some more flexible alternatives.


## Implementation in msmbayes 

Workflow, including priors, sojourn distribution graphics, model comparison 


## Covariates


## Competing exit states 
