test_that("phase parameter conversion error checking",{
  cpar_even <- c(0.1, 0.2, 0.3, 0.4)
  expect_error(canpars_to_rates(cpar_even), "should be an odd-numbered length")
  expect_error(canpars_to_rates(cpar_even), "should be an odd-numbered length")
  expect_error(canpars_to_rates("foo"), "should be numeric")
  expect_error(canpars_to_rates(c(0.1, 0.2, -0.1)), "should all be non-negative")
  expect_error(rates_to_canpars("foo"), "should be numeric")
  expect_error(rates_to_canpars(c(0.1, 0.2, -0.1)), "should all be non-negative")

  clist <- list(c(0.1), c(0.1,0.2))
  expect_error(canpars_to_rates(clist), "three components")
  clist <- list(c(0.1, 0.2), 0.1, 0.1)
  expect_error(canpars_to_rates(clist), "first component.*should have.*length")
  clist <- list(c(0.1), c(0.1,0.2), 0.1)
  expect_error(canpars_to_rates(clist), "second and third.*should have the same length")
  clist <- list(c(0.1), c(0.1,0.2), c(0.2,"foo"))
  expect_error(canpars_to_rates(clist), "numeric")

  cpars <- list(0.1, c(0.2, 0.3), c(1.2, 1.3))
  expect_warning(canpars_to_rates(cpars), "absorption.*less than or equal to sojourn")
  cpars <- list(0.1, c(0.2, 0.3), c(0.2, 0.3))
  canpars_to_rates(cpars)
  expect_error(rates_to_canpars(c(0.1, 0.2, -0.1)), "should all be non-negative")
})
