// Generated by rstantools.  Do not edit by hand.

/*
    msmbayes is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    msmbayes is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with msmbayes.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.32.2
#include <stan/model/model_header.hpp>
namespace model_msm_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 168> locations_array__ =
  {" (found before start of program)",
  " (in 'string', line 71, column 2 to column 22)",
  " (in 'string', line 73, column 2 to column 19)",
  " (in 'string', line 76, column 2 to column 18)",
  " (in 'string', line 77, column 2 to column 32)",
  " (in 'string', line 78, column 2 to column 29)",
  " (in 'string', line 80, column 4 to column 66)",
  " (in 'string', line 79, column 21 to line 81, column 3)",
  " (in 'string', line 79, column 2 to line 81, column 3)",
  " (in 'string', line 84, column 6 to column 72)",
  " (in 'string', line 83, column 19 to line 85, column 5)",
  " (in 'string', line 83, column 4 to line 85, column 5)",
  " (in 'string', line 82, column 13 to line 86, column 3)",
  " (in 'string', line 82, column 2 to line 86, column 3)",
  " (in 'string', line 89, column 10 to column 17)",
  " (in 'string', line 89, column 26 to column 27)",
  " (in 'string', line 89, column 28 to column 29)",
  " (in 'string', line 89, column 4 to column 33)",
  " (in 'string', line 90, column 11 to column 17)",
  " (in 'string', line 90, column 4 to column 24)",
  " (in 'string', line 91, column 11 to column 12)",
  " (in 'string', line 91, column 13 to column 14)",
  " (in 'string', line 91, column 4 to column 18)",
  " (in 'string', line 92, column 11 to column 12)",
  " (in 'string', line 92, column 4 to column 20)",
  " (in 'string', line 98, column 6 to column 35)",
  " (in 'string', line 100, column 1 to column 19)",
  " (in 'string', line 102, column 3 to column 73)",
  " (in 'string', line 101, column 1 to line 102, column 73)",
  " (in 'string', line 103, column 1 to column 37)",
  " (in 'string', line 99, column 25 to line 104, column 7)",
  " (in 'string', line 99, column 6 to line 104, column 7)",
  " (in 'string', line 106, column 1 to column 31)",
  " (in 'string', line 105, column 21 to line 107, column 7)",
  " (in 'string', line 105, column 6 to line 107, column 7)",
  " (in 'string', line 97, column 24 to line 108, column 5)",
  " (in 'string', line 97, column 4 to line 108, column 5)",
  " (in 'string', line 111, column 6 to column 48)",
  " (in 'string', line 112, column 6 to column 58)",
  " (in 'string', line 114, column 12 to column 32)",
  " (in 'string', line 114, column 6 to column 41)",
  " (in 'string', line 115, column 6 to column 72)",
  " (in 'string', line 129, column 1 to column 22)",
  " (in 'string', line 130, column 1 to line 133, column 2)",
  " (in 'string', line 132, column 5 to column 68)",
  " (in 'string', line 131, column 3 to line 132, column 68)",
  " (in 'string', line 134, column 1 to column 62)",
  " (in 'string', line 128, column 29 to line 135, column 7)",
  " (in 'string', line 128, column 11 to line 135, column 7)",
  " (in 'string', line 120, column 1 to line 126, column 2)",
  " (in 'string', line 122, column 5 to column 67)",
  " (in 'string', line 123, column 28 to column 69)",
  " (in 'string', line 123, column 5 to column 69)",
  " (in 'string', line 124, column 5 to column 32)",
  " (in 'string', line 121, column 25 to line 125, column 4)",
  " (in 'string', line 121, column 3 to line 125, column 4)",
  " (in 'string', line 119, column 29 to line 127, column 7)",
  " (in 'string', line 119, column 11 to line 135, column 7)",
  " (in 'string', line 118, column 1 to column 56)",
  " (in 'string', line 117, column 6 to line 135, column 7)",
  " (in 'string', line 109, column 18 to line 136, column 5)",
  " (in 'string', line 109, column 4 to line 136, column 5)",
  " (in 'string', line 138, column 13 to column 14)",
  " (in 'string', line 138, column 15 to column 16)",
  " (in 'string', line 138, column 6 to column 23)",
  " (in 'string', line 139, column 6 to column 17)",
  " (in 'string', line 141, column 1 to column 48)",
  " (in 'string', line 142, column 1 to column 39)",
  " (in 'string', line 143, column 1 to column 51)",
  " (in 'string', line 140, column 23 to line 144, column 7)",
  " (in 'string', line 140, column 6 to line 144, column 7)",
  " (in 'string', line 137, column 17 to line 145, column 5)",
  " (in 'string', line 137, column 4 to line 145, column 5)",
  " (in 'string', line 87, column 2 to line 146, column 3)",
  " (in 'string', line 150, column 4 to column 28)",
  " (in 'string', line 149, column 21 to line 151, column 3)",
  " (in 'string', line 149, column 2 to line 151, column 3)",
  " (in 'string', line 154, column 6 to column 31)",
  " (in 'string', line 153, column 19 to line 155, column 5)",
  " (in 'string', line 153, column 4 to line 155, column 5)",
  " (in 'string', line 152, column 13 to line 156, column 3)",
  " (in 'string', line 152, column 2 to line 156, column 3)",
  " (in 'string', line 157, column 2 to column 19)",
  " (in 'string', line 31, column 2 to column 17)",
  " (in 'string', line 32, column 2 to column 17)",
  " (in 'string', line 33, column 2 to column 22)",
  " (in 'string', line 34, column 8 to column 14)",
  " (in 'string', line 34, column 2 to column 42)",
  " (in 'string', line 35, column 8 to column 14)",
  " (in 'string', line 35, column 2 to column 42)",
  " (in 'string', line 36, column 8 to column 14)",
  " (in 'string', line 36, column 2 to column 30)",
  " (in 'string', line 37, column 8 to column 14)",
  " (in 'string', line 37, column 2 to column 37)",
  " (in 'string', line 39, column 8 to column 9)",
  " (in 'string', line 39, column 2 to column 42)",
  " (in 'string', line 40, column 8 to column 9)",
  " (in 'string', line 40, column 10 to column 11)",
  " (in 'string', line 40, column 2 to column 35)",
  " (in 'string', line 41, column 8 to column 9)",
  " (in 'string', line 41, column 2 to column 33)",
  " (in 'string', line 42, column 8 to column 9)",
  " (in 'string', line 42, column 2 to column 40)",
  " (in 'string', line 43, column 8 to column 9)",
  " (in 'string', line 43, column 2 to column 49)",
  " (in 'string', line 44, column 8 to column 9)",
  " (in 'string', line 44, column 2 to column 31)",
  " (in 'string', line 45, column 2 to column 23)",
  " (in 'string', line 47, column 2 to column 18)",
  " (in 'string', line 48, column 8 to column 14)",
  " (in 'string', line 48, column 2 to column 36)",
  " (in 'string', line 49, column 8 to column 14)",
  " (in 'string', line 49, column 2 to column 34)",
  " (in 'string', line 50, column 8 to column 14)",
  " (in 'string', line 50, column 2 to column 33)",
  " (in 'string', line 51, column 9 to column 16)",
  " (in 'string', line 51, column 17 to column 19)",
  " (in 'string', line 51, column 2 to column 23)",
  " (in 'string', line 52, column 8 to column 10)",
  " (in 'string', line 52, column 2 to column 27)",
  " (in 'string', line 53, column 8 to column 10)",
  " (in 'string', line 53, column 2 to column 34)",
  " (in 'string', line 55, column 2 to column 20)",
  " (in 'string', line 56, column 8 to column 12)",
  " (in 'string', line 56, column 2 to column 32)",
  " (in 'string', line 57, column 8 to column 12)",
  " (in 'string', line 57, column 2 to column 32)",
  " (in 'string', line 58, column 8 to column 12)",
  " (in 'string', line 58, column 2 to column 36)",
  " (in 'string', line 59, column 8 to column 12)",
  " (in 'string', line 59, column 2 to column 36)",
  " (in 'string', line 60, column 8 to column 12)",
  " (in 'string', line 60, column 2 to column 50)",
  " (in 'string', line 64, column 2 to column 14)",
  " (in 'string', line 65, column 8 to column 15)",
  " (in 'string', line 65, column 2 to column 28)",
  " (in 'string', line 66, column 8 to column 9)",
  " (in 'string', line 66, column 2 to column 23)",
  " (in 'string', line 67, column 8 to column 9)",
  " (in 'string', line 67, column 2 to column 22)",
  " (in 'string', line 71, column 9 to column 15)",
  " (in 'string', line 73, column 9 to column 11)",
  " (in 'string', line 77, column 8 to column 14)",
  " (in 'string', line 78, column 8 to column 10)",
  " (in 'string', line 7, column 4 to column 14)",
  " (in 'string', line 8, column 11 to column 18)",
  " (in 'string', line 8, column 4 to column 29)",
  " (in 'string', line 15, column 1 to column 15)",
  " (in 'string', line 14, column 30 to line 16, column 7)",
  " (in 'string', line 14, column 13 to line 16, column 7)",
  " (in 'string', line 13, column 1 to column 31)",
  " (in 'string', line 12, column 26 to line 14, column 7)",
  " (in 'string', line 12, column 13 to line 16, column 7)",
  " (in 'string', line 11, column 1 to column 35)",
  " (in 'string', line 10, column 19 to line 12, column 7)",
  " (in 'string', line 10, column 6 to line 16, column 7)",
  " (in 'string', line 9, column 24 to line 17, column 5)",
  " (in 'string', line 9, column 4 to line 17, column 5)",
  " (in 'string', line 18, column 4 to column 21)",
  " (in 'string', line 19, column 4 to column 21)",
  " (in 'string', line 25, column 1 to column 20)",
  " (in 'string', line 22, column 1 to column 41)",
  " (in 'string', line 21, column 55 to line 23, column 7)",
  " (in 'string', line 21, column 6 to line 25, column 20)",
  " (in 'string', line 20, column 18 to line 26, column 5)",
  " (in 'string', line 20, column 4 to line 26, column 5)",
  " (in 'string', line 27, column 4 to column 16)",
  " (in 'string', line 6, column 33 to line 28, column 3)"};
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>* = nullptr>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
validate_probs(const T0__& P_arg__, std::ostream* pstream__);
template <typename T0__,
          stan::require_all_t<stan::is_col_vector<T0__>,
                              stan::is_vt_not_complex<T0__>>*>
Eigen::Matrix<stan::promote_args_t<stan::base_type_t<T0__>>,-1,1>
validate_probs(const T0__& P_arg__, std::ostream* pstream__) {
  using local_scalar_t__ = stan::promote_args_t<stan::base_type_t<T0__>>;
  int current_statement__ = 0;
  const auto& P = stan::math::to_ref(P_arg__);
  static constexpr bool propto__ = true;
  // suppress unused var warning
  (void) propto__;
  local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
  // suppress unused var warning
  (void) DUMMY_VAR__;
  try {
    local_scalar_t__ psum = DUMMY_VAR__;
    current_statement__ = 145;
    stan::math::validate_non_negative_index("Pret", "size(P)",
      stan::math::size(P));
    Eigen::Matrix<local_scalar_t__,-1,1> Pret =
      Eigen::Matrix<local_scalar_t__,-1,1>::Constant(stan::math::size(P),
        DUMMY_VAR__);
    current_statement__ = 146;
    stan::model::assign(Pret, P, "assigning variable Pret");
    current_statement__ = 157;
    for (int i = 1; i <= stan::math::size(P); ++i) {
      current_statement__ = 155;
      if (stan::math::logical_gt(
            stan::model::rvalue(P, "P", stan::model::index_uni(i)), 1)) {
        current_statement__ = 153;
        stan::model::assign(Pret, (1 - stan::math::machine_precision()),
          "assigning variable Pret", stan::model::index_uni(i));
      } else {
        current_statement__ = 152;
        if (stan::math::logical_lt(
              stan::model::rvalue(P, "P", stan::model::index_uni(i)), 0)) {
          current_statement__ = 150;
          stan::model::assign(Pret, stan::math::machine_precision(),
            "assigning variable Pret", stan::model::index_uni(i));
        } else {
          current_statement__ = 149;
          if (stan::math::is_nan(
                stan::model::rvalue(P, "P", stan::model::index_uni(i)))) {
            current_statement__ = 147;
            stan::model::assign(Pret, 0.5, "assigning variable Pret",
              stan::model::index_uni(i));
          }
        }
      }
    }
    current_statement__ = 158;
    psum = stan::math::sum(Pret);
    local_scalar_t__ eps = DUMMY_VAR__;
    current_statement__ = 159;
    eps = 0.001;
    current_statement__ = 165;
    if (stan::math::logical_neq(psum, 1)) {
      current_statement__ = 163;
      if ((stan::math::primitive_value(
             (stan::math::primitive_value(stan::math::logical_lt(psum, eps))
             || stan::math::primitive_value(stan::math::is_nan(psum))))
          || stan::math::primitive_value(stan::math::is_inf(psum)))) {
        current_statement__ = 161;
        stan::model::assign(Pret,
          stan::math::rep_vector((1.0 / stan::math::size(P)),
            stan::math::size(P)), "assigning variable Pret");
      } else {
        current_statement__ = 160;
        stan::model::assign(Pret,
          stan::math::divide(stan::model::deep_copy(Pret), psum),
          "assigning variable Pret");
      }
    }
    current_statement__ = 166;
    return Pret;
  } catch (const std::exception& e) {
    stan::lang::rethrow_located(e, locations_array__[current_statement__]);
  }
}
#include <stan_meta_header.hpp>
class model_msm final : public model_base_crtp<model_msm> {
private:
  int K;
  int N;
  int nqpars;
  std::vector<int> qrow;
  std::vector<int> qcol;
  std::vector<double> logqmean;
  std::vector<double> logqsd;
  std::vector<int> fromstate;
  std::vector<std::vector<int>> ntostate;
  std::vector<double> timelag;
  std::vector<int> obstype;
  std::vector<int> exactdeath_state;
  std::vector<int> covind;
  int ncovind;
  int nx;
  std::vector<int> xstart;
  std::vector<int> xend;
  std::vector<int> nxq;
  Eigen::Matrix<double,-1,-1> X_data__;
  std::vector<double> loghrmean;
  std::vector<double> loghrsd;
  int nsoj;
  std::vector<int> sojy;
  std::vector<int> sojn;
  std::vector<int> sojstate;
  std::vector<double> sojtime;
  std::vector<int> sojtlcid;
  int nptrans;
  std::vector<int> nzinds;
  std::vector<int> nzifrom;
  std::vector<int> nzilen;
  Eigen::Map<Eigen::Matrix<double,-1,-1>> X{nullptr, 0, 0};
public:
  ~model_msm() {}
  model_msm(stan::io::var_context& context__, unsigned int random_seed__ = 0,
            std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double;
    boost::ecuyer1988 base_rng__ =
      stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_msm_namespace::model_msm";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 83;
      context__.validate_dims("data initialization", "K", "int",
        std::vector<size_t>{});
      K = std::numeric_limits<int>::min();
      current_statement__ = 83;
      K = context__.vals_i("K")[(1 - 1)];
      current_statement__ = 83;
      stan::math::check_greater_or_equal(function__, "K", K, 1);
      current_statement__ = 84;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 84;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 84;
      stan::math::check_greater_or_equal(function__, "N", N, 1);
      current_statement__ = 85;
      context__.validate_dims("data initialization", "nqpars", "int",
        std::vector<size_t>{});
      nqpars = std::numeric_limits<int>::min();
      current_statement__ = 85;
      nqpars = context__.vals_i("nqpars")[(1 - 1)];
      current_statement__ = 85;
      stan::math::check_greater_or_equal(function__, "nqpars", nqpars, 0);
      current_statement__ = 86;
      stan::math::validate_non_negative_index("qrow", "nqpars", nqpars);
      current_statement__ = 87;
      context__.validate_dims("data initialization", "qrow", "int",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      qrow = std::vector<int>(nqpars, std::numeric_limits<int>::min());
      current_statement__ = 87;
      qrow = context__.vals_i("qrow");
      current_statement__ = 87;
      stan::math::check_greater_or_equal(function__, "qrow", qrow, 1);
      current_statement__ = 87;
      stan::math::check_less_or_equal(function__, "qrow", qrow, K);
      current_statement__ = 88;
      stan::math::validate_non_negative_index("qcol", "nqpars", nqpars);
      current_statement__ = 89;
      context__.validate_dims("data initialization", "qcol", "int",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      qcol = std::vector<int>(nqpars, std::numeric_limits<int>::min());
      current_statement__ = 89;
      qcol = context__.vals_i("qcol");
      current_statement__ = 89;
      stan::math::check_greater_or_equal(function__, "qcol", qcol, 1);
      current_statement__ = 89;
      stan::math::check_less_or_equal(function__, "qcol", qcol, K);
      current_statement__ = 90;
      stan::math::validate_non_negative_index("logqmean", "nqpars", nqpars);
      current_statement__ = 91;
      context__.validate_dims("data initialization", "logqmean", "double",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      logqmean = std::vector<double>(nqpars,
                   std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 91;
      logqmean = context__.vals_r("logqmean");
      current_statement__ = 92;
      stan::math::validate_non_negative_index("logqsd", "nqpars", nqpars);
      current_statement__ = 93;
      context__.validate_dims("data initialization", "logqsd", "double",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      logqsd = std::vector<double>(nqpars,
                 std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 93;
      logqsd = context__.vals_r("logqsd");
      current_statement__ = 93;
      stan::math::check_greater_or_equal(function__, "logqsd", logqsd, 0);
      current_statement__ = 94;
      stan::math::validate_non_negative_index("fromstate", "N", N);
      current_statement__ = 95;
      context__.validate_dims("data initialization", "fromstate", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      fromstate = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 95;
      fromstate = context__.vals_i("fromstate");
      current_statement__ = 95;
      stan::math::check_greater_or_equal(function__, "fromstate", fromstate,
        1);
      current_statement__ = 95;
      stan::math::check_less_or_equal(function__, "fromstate", fromstate, K);
      current_statement__ = 96;
      stan::math::validate_non_negative_index("ntostate", "N", N);
      current_statement__ = 97;
      stan::math::validate_non_negative_index("ntostate", "K", K);
      current_statement__ = 98;
      context__.validate_dims("data initialization", "ntostate", "int",
        std::vector<size_t>{static_cast<size_t>(N), static_cast<size_t>(K)});
      ntostate = std::vector<std::vector<int>>(N,
                   std::vector<int>(K, std::numeric_limits<int>::min()));
      {
        std::vector<int> ntostate_flat__;
        current_statement__ = 98;
        ntostate_flat__ = context__.vals_i("ntostate");
        current_statement__ = 98;
        pos__ = 1;
        current_statement__ = 98;
        for (int sym1__ = 1; sym1__ <= K; ++sym1__) {
          current_statement__ = 98;
          for (int sym2__ = 1; sym2__ <= N; ++sym2__) {
            current_statement__ = 98;
            stan::model::assign(ntostate, ntostate_flat__[(pos__ - 1)],
              "assigning variable ntostate", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 98;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 98;
      stan::math::check_greater_or_equal(function__, "ntostate", ntostate, 0);
      current_statement__ = 99;
      stan::math::validate_non_negative_index("timelag", "N", N);
      current_statement__ = 100;
      context__.validate_dims("data initialization", "timelag", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      timelag = std::vector<double>(N,
                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 100;
      timelag = context__.vals_r("timelag");
      current_statement__ = 100;
      stan::math::check_greater_or_equal(function__, "timelag", timelag, 0);
      current_statement__ = 101;
      stan::math::validate_non_negative_index("obstype", "N", N);
      current_statement__ = 102;
      context__.validate_dims("data initialization", "obstype", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      obstype = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 102;
      obstype = context__.vals_i("obstype");
      current_statement__ = 102;
      stan::math::check_greater_or_equal(function__, "obstype", obstype, 1);
      current_statement__ = 102;
      stan::math::check_less_or_equal(function__, "obstype", obstype, 3);
      current_statement__ = 103;
      stan::math::validate_non_negative_index("exactdeath_state", "N", N);
      current_statement__ = 104;
      context__.validate_dims("data initialization", "exactdeath_state",
        "int", std::vector<size_t>{static_cast<size_t>(N)});
      exactdeath_state = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 104;
      exactdeath_state = context__.vals_i("exactdeath_state");
      current_statement__ = 104;
      stan::math::check_greater_or_equal(function__, "exactdeath_state",
        exactdeath_state, 0);
      current_statement__ = 104;
      stan::math::check_less_or_equal(function__, "exactdeath_state",
        exactdeath_state, K);
      current_statement__ = 105;
      stan::math::validate_non_negative_index("covind", "N", N);
      current_statement__ = 106;
      context__.validate_dims("data initialization", "covind", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      covind = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 106;
      covind = context__.vals_i("covind");
      current_statement__ = 106;
      stan::math::check_greater_or_equal(function__, "covind", covind, 1);
      current_statement__ = 107;
      context__.validate_dims("data initialization", "ncovind", "int",
        std::vector<size_t>{});
      ncovind = std::numeric_limits<int>::min();
      current_statement__ = 107;
      ncovind = context__.vals_i("ncovind")[(1 - 1)];
      current_statement__ = 107;
      stan::math::check_greater_or_equal(function__, "ncovind", ncovind, 1);
      current_statement__ = 108;
      context__.validate_dims("data initialization", "nx", "int",
        std::vector<size_t>{});
      nx = std::numeric_limits<int>::min();
      current_statement__ = 108;
      nx = context__.vals_i("nx")[(1 - 1)];
      current_statement__ = 108;
      stan::math::check_greater_or_equal(function__, "nx", nx, 0);
      current_statement__ = 109;
      stan::math::validate_non_negative_index("xstart", "nqpars", nqpars);
      current_statement__ = 110;
      context__.validate_dims("data initialization", "xstart", "int",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      xstart = std::vector<int>(nqpars, std::numeric_limits<int>::min());
      current_statement__ = 110;
      xstart = context__.vals_i("xstart");
      current_statement__ = 110;
      stan::math::check_greater_or_equal(function__, "xstart", xstart, 0);
      current_statement__ = 111;
      stan::math::validate_non_negative_index("xend", "nqpars", nqpars);
      current_statement__ = 112;
      context__.validate_dims("data initialization", "xend", "int",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      xend = std::vector<int>(nqpars, std::numeric_limits<int>::min());
      current_statement__ = 112;
      xend = context__.vals_i("xend");
      current_statement__ = 112;
      stan::math::check_greater_or_equal(function__, "xend", xend, 0);
      current_statement__ = 113;
      stan::math::validate_non_negative_index("nxq", "nqpars", nqpars);
      current_statement__ = 114;
      context__.validate_dims("data initialization", "nxq", "int",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      nxq = std::vector<int>(nqpars, std::numeric_limits<int>::min());
      current_statement__ = 114;
      nxq = context__.vals_i("nxq");
      current_statement__ = 114;
      stan::math::check_greater_or_equal(function__, "nxq", nxq, 0);
      current_statement__ = 115;
      stan::math::validate_non_negative_index("X", "ncovind", ncovind);
      current_statement__ = 116;
      stan::math::validate_non_negative_index("X", "nx", nx);
      current_statement__ = 117;
      context__.validate_dims("data initialization", "X", "double",
        std::vector<size_t>{static_cast<size_t>(ncovind),
          static_cast<size_t>(nx)});
      X_data__ = Eigen::Matrix<double,-1,-1>::Constant(ncovind, nx,
                   std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double,-1,-1>>(X_data__.data(),
        ncovind, nx);
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 117;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 117;
        pos__ = 1;
        current_statement__ = 117;
        for (int sym1__ = 1; sym1__ <= nx; ++sym1__) {
          current_statement__ = 117;
          for (int sym2__ = 1; sym2__ <= ncovind; ++sym2__) {
            current_statement__ = 117;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
              stan::model::index_uni(sym1__));
            current_statement__ = 117;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 118;
      stan::math::validate_non_negative_index("loghrmean", "nx", nx);
      current_statement__ = 119;
      context__.validate_dims("data initialization", "loghrmean", "double",
        std::vector<size_t>{static_cast<size_t>(nx)});
      loghrmean = std::vector<double>(nx,
                    std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 119;
      loghrmean = context__.vals_r("loghrmean");
      current_statement__ = 120;
      stan::math::validate_non_negative_index("loghrsd", "nx", nx);
      current_statement__ = 121;
      context__.validate_dims("data initialization", "loghrsd", "double",
        std::vector<size_t>{static_cast<size_t>(nx)});
      loghrsd = std::vector<double>(nx,
                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 121;
      loghrsd = context__.vals_r("loghrsd");
      current_statement__ = 121;
      stan::math::check_greater_or_equal(function__, "loghrsd", loghrsd, 0);
      current_statement__ = 122;
      context__.validate_dims("data initialization", "nsoj", "int",
        std::vector<size_t>{});
      nsoj = std::numeric_limits<int>::min();
      current_statement__ = 122;
      nsoj = context__.vals_i("nsoj")[(1 - 1)];
      current_statement__ = 122;
      stan::math::check_greater_or_equal(function__, "nsoj", nsoj, 0);
      current_statement__ = 123;
      stan::math::validate_non_negative_index("sojy", "nsoj", nsoj);
      current_statement__ = 124;
      context__.validate_dims("data initialization", "sojy", "int",
        std::vector<size_t>{static_cast<size_t>(nsoj)});
      sojy = std::vector<int>(nsoj, std::numeric_limits<int>::min());
      current_statement__ = 124;
      sojy = context__.vals_i("sojy");
      current_statement__ = 124;
      stan::math::check_greater_or_equal(function__, "sojy", sojy, 0);
      current_statement__ = 125;
      stan::math::validate_non_negative_index("sojn", "nsoj", nsoj);
      current_statement__ = 126;
      context__.validate_dims("data initialization", "sojn", "int",
        std::vector<size_t>{static_cast<size_t>(nsoj)});
      sojn = std::vector<int>(nsoj, std::numeric_limits<int>::min());
      current_statement__ = 126;
      sojn = context__.vals_i("sojn");
      current_statement__ = 126;
      stan::math::check_greater_or_equal(function__, "sojn", sojn, 0);
      current_statement__ = 127;
      stan::math::validate_non_negative_index("sojstate", "nsoj", nsoj);
      current_statement__ = 128;
      context__.validate_dims("data initialization", "sojstate", "int",
        std::vector<size_t>{static_cast<size_t>(nsoj)});
      sojstate = std::vector<int>(nsoj, std::numeric_limits<int>::min());
      current_statement__ = 128;
      sojstate = context__.vals_i("sojstate");
      current_statement__ = 128;
      stan::math::check_greater_or_equal(function__, "sojstate", sojstate, 1);
      current_statement__ = 129;
      stan::math::validate_non_negative_index("sojtime", "nsoj", nsoj);
      current_statement__ = 130;
      context__.validate_dims("data initialization", "sojtime", "double",
        std::vector<size_t>{static_cast<size_t>(nsoj)});
      sojtime = std::vector<double>(nsoj,
                  std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 130;
      sojtime = context__.vals_r("sojtime");
      current_statement__ = 130;
      stan::math::check_greater_or_equal(function__, "sojtime", sojtime, 0);
      current_statement__ = 131;
      stan::math::validate_non_negative_index("sojtlcid", "nsoj", nsoj);
      current_statement__ = 132;
      context__.validate_dims("data initialization", "sojtlcid", "int",
        std::vector<size_t>{static_cast<size_t>(nsoj)});
      sojtlcid = std::vector<int>(nsoj, std::numeric_limits<int>::min());
      current_statement__ = 132;
      sojtlcid = context__.vals_i("sojtlcid");
      current_statement__ = 132;
      stan::math::check_greater_or_equal(function__, "sojtlcid", sojtlcid, 1);
      current_statement__ = 132;
      stan::math::check_less_or_equal(function__, "sojtlcid", sojtlcid,
        ncovind);
      current_statement__ = 133;
      context__.validate_dims("data initialization", "nptrans", "int",
        std::vector<size_t>{});
      nptrans = std::numeric_limits<int>::min();
      current_statement__ = 133;
      nptrans = context__.vals_i("nptrans")[(1 - 1)];
      current_statement__ = 134;
      stan::math::validate_non_negative_index("nzinds", "nptrans", nptrans);
      current_statement__ = 135;
      context__.validate_dims("data initialization", "nzinds", "int",
        std::vector<size_t>{static_cast<size_t>(nptrans)});
      nzinds = std::vector<int>(nptrans, std::numeric_limits<int>::min());
      current_statement__ = 135;
      nzinds = context__.vals_i("nzinds");
      current_statement__ = 136;
      stan::math::validate_non_negative_index("nzifrom", "K", K);
      current_statement__ = 137;
      context__.validate_dims("data initialization", "nzifrom", "int",
        std::vector<size_t>{static_cast<size_t>(K)});
      nzifrom = std::vector<int>(K, std::numeric_limits<int>::min());
      current_statement__ = 137;
      nzifrom = context__.vals_i("nzifrom");
      current_statement__ = 138;
      stan::math::validate_non_negative_index("nzilen", "K", K);
      current_statement__ = 139;
      context__.validate_dims("data initialization", "nzilen", "int",
        std::vector<size_t>{static_cast<size_t>(K)});
      nzilen = std::vector<int>(K, std::numeric_limits<int>::min());
      current_statement__ = 139;
      nzilen = context__.vals_i("nzilen");
      current_statement__ = 140;
      stan::math::validate_non_negative_index("logq", "nqpars", nqpars);
      current_statement__ = 141;
      stan::math::validate_non_negative_index("loghr", "nx", nx);
      current_statement__ = 142;
      stan::math::validate_non_negative_index("prior_logq", "nqpars", nqpars);
      current_statement__ = 143;
      stan::math::validate_non_negative_index("prior_loghr", "nx", nx);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = nqpars + nx;
  }
  inline std::string model_name() const final {
    return "model_msm";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.32.2",
             "stancflags = --allow-undefined"};
  }
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ = "model_msm_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> logq =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nqpars, DUMMY_VAR__);
      current_statement__ = 1;
      logq = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nqpars);
      Eigen::Matrix<local_scalar_t__,-1,1> loghr =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nx, DUMMY_VAR__);
      current_statement__ = 2;
      loghr = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nx);
      local_scalar_t__ loglik = DUMMY_VAR__;
      current_statement__ = 3;
      loglik = 0;
      std::vector<local_scalar_t__> prior_logq =
        std::vector<local_scalar_t__>(nqpars, DUMMY_VAR__);
      std::vector<local_scalar_t__> prior_loghr =
        std::vector<local_scalar_t__>(nx, DUMMY_VAR__);
      current_statement__ = 8;
      for (int i = 1; i <= nqpars; ++i) {
        current_statement__ = 6;
        stan::model::assign(prior_logq,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(logq, "logq", stan::model::index_uni(i)),
            stan::model::rvalue(logqmean, "logqmean",
              stan::model::index_uni(i)),
            stan::model::rvalue(logqsd, "logqsd", stan::model::index_uni(i))),
          "assigning variable prior_logq", stan::model::index_uni(i));
      }
      current_statement__ = 13;
      if (stan::math::logical_gt(nx, 0)) {
        current_statement__ = 11;
        for (int i = 1; i <= nx; ++i) {
          current_statement__ = 9;
          stan::model::assign(prior_loghr,
            stan::math::normal_lpdf<false>(
              stan::model::rvalue(loghr, "loghr", stan::model::index_uni(i)),
              stan::model::rvalue(loghrmean, "loghrmean",
                stan::model::index_uni(i)),
              stan::model::rvalue(loghrsd, "loghrsd",
                stan::model::index_uni(i))),
            "assigning variable prior_loghr", stan::model::index_uni(i));
        }
      }
      {
        current_statement__ = 14;
        stan::math::validate_non_negative_index("Q", "ncovind", ncovind);
        current_statement__ = 15;
        stan::math::validate_non_negative_index("Q", "K", K);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("Q", "K", K);
        std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>> Q =
          std::vector<Eigen::Matrix<local_scalar_t__,-1,-1>>(ncovind,
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, K,
              DUMMY_VAR__));
        current_statement__ = 18;
        stan::math::validate_non_negative_index("qtmp", "nqpars", nqpars);
        Eigen::Matrix<local_scalar_t__,-1,1> qtmp =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nqpars, DUMMY_VAR__);
        current_statement__ = 20;
        stan::math::validate_non_negative_index("P", "K", K);
        current_statement__ = 21;
        stan::math::validate_non_negative_index("P", "K", K);
        Eigen::Matrix<local_scalar_t__,-1,-1> P =
          Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, K, DUMMY_VAR__);
        current_statement__ = 23;
        stan::math::validate_non_negative_index("probs", "K", K);
        Eigen::Matrix<local_scalar_t__,-1,1> probs =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(K, DUMMY_VAR__);
        current_statement__ = 36;
        for (int j = 1; j <= ncovind; ++j) {
          current_statement__ = 25;
          stan::model::assign(Q, stan::math::rep_matrix(0, K, K),
            "assigning variable Q", stan::model::index_uni(j),
            stan::model::index_omni(), stan::model::index_omni());
          current_statement__ = 31;
          for (int i = 1; i <= nqpars; ++i) {
            current_statement__ = 26;
            stan::model::assign(qtmp,
              stan::model::rvalue(logq, "logq", stan::model::index_uni(i)),
              "assigning variable qtmp", stan::model::index_uni(i));
            current_statement__ = 28;
            if (stan::math::logical_gt(
                  stan::model::rvalue(nxq, "nxq", stan::model::index_uni(i)),
                  0)) {
              current_statement__ = 27;
              stan::model::assign(qtmp,
                (stan::model::rvalue(qtmp, "qtmp", stan::model::index_uni(i))
                +
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(j),
                    stan::model::index_min_max(
                      stan::model::rvalue(xstart, "xstart",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(xend, "xend",
                        stan::model::index_uni(i)))),
                  stan::model::rvalue(loghr, "loghr",
                    stan::model::index_min_max(
                      stan::model::rvalue(xstart, "xstart",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(xend, "xend",
                        stan::model::index_uni(i)))))),
                "assigning variable qtmp", stan::model::index_uni(i));
            }
            current_statement__ = 29;
            stan::model::assign(Q,
              stan::math::exp(
                stan::model::rvalue(qtmp, "qtmp", stan::model::index_uni(i))),
              "assigning variable Q", stan::model::index_uni(j),
              stan::model::index_uni(
                stan::model::rvalue(qrow, "qrow", stan::model::index_uni(i))),
              stan::model::index_uni(
                stan::model::rvalue(qcol, "qcol", stan::model::index_uni(i))));
          }
          current_statement__ = 34;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 32;
            stan::model::assign(Q,
              -stan::math::sum(
                 stan::model::rvalue(Q, "Q", stan::model::index_uni(j),
                   stan::model::index_uni(k),
                   stan::model::index_min_max(1, K))),
              "assigning variable Q", stan::model::index_uni(j),
              stan::model::index_uni(k), stan::model::index_uni(k));
          }
        }
        current_statement__ = 61;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 37;
          stan::model::assign(P,
            stan::math::matrix_exp(
              stan::math::multiply(
                stan::model::rvalue(Q, "Q",
                  stan::model::index_uni(
                    stan::model::rvalue(covind, "covind",
                      stan::model::index_uni(i))), stan::model::index_omni(),
                  stan::model::index_omni()),
                stan::model::rvalue(timelag, "timelag",
                  stan::model::index_uni(i)))), "assigning variable P");
          current_statement__ = 38;
          stan::model::assign(probs,
            validate_probs(
              stan::math::to_vector(
                stan::model::rvalue(P, "P",
                  stan::model::index_uni(
                    stan::model::rvalue(fromstate, "fromstate",
                      stan::model::index_uni(i))), stan::model::index_omni())),
              pstream__), "assigning variable probs");
          current_statement__ = 39;
          stan::math::validate_non_negative_index("nz",
            "nzilen[fromstate[i]]",
            stan::model::rvalue(nzilen, "nzilen",
              stan::model::index_uni(
                stan::model::rvalue(fromstate, "fromstate",
                  stan::model::index_uni(i)))));
          std::vector<int> nz =
            std::vector<int>(stan::model::rvalue(nzilen, "nzilen",
                               stan::model::index_uni(
                                 stan::model::rvalue(fromstate, "fromstate",
                                   stan::model::index_uni(i)))),
              std::numeric_limits<int>::min());
          current_statement__ = 41;
          stan::model::assign(nz,
            stan::math::segment(nzinds,
              stan::model::rvalue(nzifrom, "nzifrom",
                stan::model::index_uni(
                  stan::model::rvalue(fromstate, "fromstate",
                    stan::model::index_uni(i)))),
              stan::model::rvalue(nzilen, "nzilen",
                stan::model::index_uni(
                  stan::model::rvalue(fromstate, "fromstate",
                    stan::model::index_uni(i))))), "assigning variable nz");
          current_statement__ = 59;
          if (stan::math::logical_eq(
                stan::model::rvalue(obstype, "obstype",
                  stan::model::index_uni(i)), 1)) {
            current_statement__ = 58;
            loglik = (loglik +
              stan::math::multinomial_lpmf<false>(
                stan::model::rvalue(ntostate, "ntostate",
                  stan::model::index_uni(i), stan::model::index_multi(nz)),
                stan::model::rvalue(probs, "probs",
                  stan::model::index_multi(nz))));
          } else {
            current_statement__ = 57;
            if (stan::math::logical_eq(
                  stan::model::rvalue(obstype, "obstype",
                    stan::model::index_uni(i)), 2)) {
              current_statement__ = 49;
              for (int sym1__ = 1; sym1__ <= stan::math::size(nz); ++sym1__) {
                int k;
                current_statement__ = 49;
                k = nz[(sym1__ - 1)];
                current_statement__ = 55;
                if (stan::math::logical_gt(
                      stan::model::rvalue(ntostate, "ntostate",
                        stan::model::index_uni(i), stan::model::index_uni(k)),
                      0)) {
                  local_scalar_t__ lp = DUMMY_VAR__;
                  current_statement__ = 50;
                  lp = (stan::model::rvalue(Q, "Q",
                          stan::model::index_uni(
                            stan::model::rvalue(covind, "covind",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(
                            stan::model::rvalue(fromstate, "fromstate",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(
                            stan::model::rvalue(fromstate, "fromstate",
                              stan::model::index_uni(i))))
                    *
                    stan::model::rvalue(timelag, "timelag",
                      stan::model::index_uni(i)));
                  current_statement__ = 52;
                  if (stan::math::logical_neq(k,
                        stan::model::rvalue(fromstate, "fromstate",
                          stan::model::index_uni(i)))) {
                    current_statement__ = 51;
                    lp = (lp +
                      stan::math::log(
                        stan::model::rvalue(Q, "Q",
                          stan::model::index_uni(
                            stan::model::rvalue(covind, "covind",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(
                            stan::model::rvalue(fromstate, "fromstate",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(k))));
                  }
                  current_statement__ = 53;
                  loglik = (loglik +
                    (stan::model::rvalue(ntostate, "ntostate",
                       stan::model::index_uni(i), stan::model::index_uni(k))
                    * lp));
                }
              }
            } else {
              current_statement__ = 48;
              if (stan::math::logical_eq(
                    stan::model::rvalue(obstype, "obstype",
                      stan::model::index_uni(i)), 3)) {
                local_scalar_t__ pexactdeath = DUMMY_VAR__;
                current_statement__ = 42;
                pexactdeath = 0;
                current_statement__ = 43;
                for (int sym1__ = 1; sym1__ <= stan::math::size(nz); ++sym1__) {
                  int k;
                  current_statement__ = 43;
                  k = nz[(sym1__ - 1)];
                  current_statement__ = 45;
                  if (stan::math::logical_neq(k,
                        stan::model::rvalue(exactdeath_state,
                          "exactdeath_state", stan::model::index_uni(i)))) {
                    current_statement__ = 44;
                    pexactdeath = (pexactdeath +
                      (stan::model::rvalue(probs, "probs",
                         stan::model::index_uni(k))
                      *
                      stan::model::rvalue(Q, "Q",
                        stan::model::index_uni(
                          stan::model::rvalue(covind, "covind",
                            stan::model::index_uni(i))),
                        stan::model::index_uni(k),
                        stan::model::index_uni(
                          stan::model::rvalue(exactdeath_state,
                            "exactdeath_state", stan::model::index_uni(i))))));
                  }
                }
                current_statement__ = 46;
                loglik = (loglik +
                  (stan::model::rvalue(ntostate, "ntostate",
                     stan::model::index_uni(i),
                     stan::model::index_uni(
                       stan::model::rvalue(exactdeath_state,
                         "exactdeath_state", stan::model::index_uni(i))))
                  * stan::math::log(pexactdeath)));
              }
            }
          }
        }
        current_statement__ = 72;
        if (stan::math::logical_gt(nsoj, 0)) {
          current_statement__ = 62;
          stan::math::validate_non_negative_index("Ptmp", "K", K);
          current_statement__ = 63;
          stan::math::validate_non_negative_index("Ptmp", "K", K);
          Eigen::Matrix<local_scalar_t__,-1,-1> Ptmp =
            Eigen::Matrix<local_scalar_t__,-1,-1>::Constant(K, K,
              DUMMY_VAR__);
          local_scalar_t__ sprob = DUMMY_VAR__;
          current_statement__ = 70;
          for (int i = 1; i <= nsoj; ++i) {
            current_statement__ = 66;
            stan::model::assign(Ptmp,
              stan::math::matrix_exp(
                stan::math::multiply(
                  stan::model::rvalue(Q, "Q",
                    stan::model::index_uni(
                      stan::model::rvalue(sojtlcid, "sojtlcid",
                        stan::model::index_uni(i))),
                    stan::model::index_omni(), stan::model::index_omni()),
                  stan::model::rvalue(sojtime, "sojtime",
                    stan::model::index_uni(i)))), "assigning variable Ptmp");
            current_statement__ = 67;
            sprob = stan::model::rvalue(Ptmp, "Ptmp",
                      stan::model::index_uni(
                        stan::model::rvalue(sojstate, "sojstate",
                          stan::model::index_uni(i))),
                      stan::model::index_uni(
                        stan::model::rvalue(sojstate, "sojstate",
                          stan::model::index_uni(i))));
            current_statement__ = 68;
            loglik = (loglik +
              stan::math::binomial_lpmf<false>(
                stan::model::rvalue(sojy, "sojy", stan::model::index_uni(i)),
                stan::model::rvalue(sojn, "sojn", stan::model::index_uni(i)),
                sprob));
          }
        }
      }
      {
        current_statement__ = 76;
        for (int i = 1; i <= nqpars; ++i) {
          current_statement__ = 74;
          lp_accum__.add(stan::model::rvalue(prior_logq, "prior_logq",
                           stan::model::index_uni(i)));
        }
        current_statement__ = 81;
        if (stan::math::logical_gt(nx, 0)) {
          current_statement__ = 79;
          for (int i = 1; i <= nx; ++i) {
            current_statement__ = 77;
            lp_accum__.add(stan::model::rvalue(prior_loghr, "prior_loghr",
                             stan::model::index_uni(i)));
          }
        }
        current_statement__ = 82;
        lp_accum__.add(loglik);
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    static constexpr const char* function__ =
      "model_msm_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> logq =
        Eigen::Matrix<double,-1,1>::Constant(nqpars,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      logq = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nqpars);
      Eigen::Matrix<double,-1,1> loghr =
        Eigen::Matrix<double,-1,1>::Constant(nx,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      loghr = in__.template read<Eigen::Matrix<local_scalar_t__,-1,1>>(nx);
      double loglik = std::numeric_limits<double>::quiet_NaN();
      std::vector<double> prior_logq =
        std::vector<double>(nqpars, std::numeric_limits<double>::quiet_NaN());
      std::vector<double> prior_loghr =
        std::vector<double>(nx, std::numeric_limits<double>::quiet_NaN());
      out__.write(logq);
      out__.write(loghr);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      current_statement__ = 3;
      loglik = 0;
      current_statement__ = 8;
      for (int i = 1; i <= nqpars; ++i) {
        current_statement__ = 6;
        stan::model::assign(prior_logq,
          stan::math::normal_lpdf<false>(
            stan::model::rvalue(logq, "logq", stan::model::index_uni(i)),
            stan::model::rvalue(logqmean, "logqmean",
              stan::model::index_uni(i)),
            stan::model::rvalue(logqsd, "logqsd", stan::model::index_uni(i))),
          "assigning variable prior_logq", stan::model::index_uni(i));
      }
      current_statement__ = 13;
      if (stan::math::logical_gt(nx, 0)) {
        current_statement__ = 11;
        for (int i = 1; i <= nx; ++i) {
          current_statement__ = 9;
          stan::model::assign(prior_loghr,
            stan::math::normal_lpdf<false>(
              stan::model::rvalue(loghr, "loghr", stan::model::index_uni(i)),
              stan::model::rvalue(loghrmean, "loghrmean",
                stan::model::index_uni(i)),
              stan::model::rvalue(loghrsd, "loghrsd",
                stan::model::index_uni(i))),
            "assigning variable prior_loghr", stan::model::index_uni(i));
        }
      }
      {
        current_statement__ = 14;
        stan::math::validate_non_negative_index("Q", "ncovind", ncovind);
        current_statement__ = 15;
        stan::math::validate_non_negative_index("Q", "K", K);
        current_statement__ = 16;
        stan::math::validate_non_negative_index("Q", "K", K);
        std::vector<Eigen::Matrix<double,-1,-1>> Q =
          std::vector<Eigen::Matrix<double,-1,-1>>(ncovind,
            Eigen::Matrix<double,-1,-1>::Constant(K, K,
              std::numeric_limits<double>::quiet_NaN()));
        current_statement__ = 18;
        stan::math::validate_non_negative_index("qtmp", "nqpars", nqpars);
        Eigen::Matrix<double,-1,1> qtmp =
          Eigen::Matrix<double,-1,1>::Constant(nqpars,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 20;
        stan::math::validate_non_negative_index("P", "K", K);
        current_statement__ = 21;
        stan::math::validate_non_negative_index("P", "K", K);
        Eigen::Matrix<double,-1,-1> P =
          Eigen::Matrix<double,-1,-1>::Constant(K, K,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 23;
        stan::math::validate_non_negative_index("probs", "K", K);
        Eigen::Matrix<double,-1,1> probs =
          Eigen::Matrix<double,-1,1>::Constant(K,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 36;
        for (int j = 1; j <= ncovind; ++j) {
          current_statement__ = 25;
          stan::model::assign(Q, stan::math::rep_matrix(0, K, K),
            "assigning variable Q", stan::model::index_uni(j),
            stan::model::index_omni(), stan::model::index_omni());
          current_statement__ = 31;
          for (int i = 1; i <= nqpars; ++i) {
            current_statement__ = 26;
            stan::model::assign(qtmp,
              stan::model::rvalue(logq, "logq", stan::model::index_uni(i)),
              "assigning variable qtmp", stan::model::index_uni(i));
            current_statement__ = 28;
            if (stan::math::logical_gt(
                  stan::model::rvalue(nxq, "nxq", stan::model::index_uni(i)),
                  0)) {
              current_statement__ = 27;
              stan::model::assign(qtmp,
                (stan::model::rvalue(qtmp, "qtmp", stan::model::index_uni(i))
                +
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(j),
                    stan::model::index_min_max(
                      stan::model::rvalue(xstart, "xstart",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(xend, "xend",
                        stan::model::index_uni(i)))),
                  stan::model::rvalue(loghr, "loghr",
                    stan::model::index_min_max(
                      stan::model::rvalue(xstart, "xstart",
                        stan::model::index_uni(i)),
                      stan::model::rvalue(xend, "xend",
                        stan::model::index_uni(i)))))),
                "assigning variable qtmp", stan::model::index_uni(i));
            }
            current_statement__ = 29;
            stan::model::assign(Q,
              stan::math::exp(
                stan::model::rvalue(qtmp, "qtmp", stan::model::index_uni(i))),
              "assigning variable Q", stan::model::index_uni(j),
              stan::model::index_uni(
                stan::model::rvalue(qrow, "qrow", stan::model::index_uni(i))),
              stan::model::index_uni(
                stan::model::rvalue(qcol, "qcol", stan::model::index_uni(i))));
          }
          current_statement__ = 34;
          for (int k = 1; k <= K; ++k) {
            current_statement__ = 32;
            stan::model::assign(Q,
              -stan::math::sum(
                 stan::model::rvalue(Q, "Q", stan::model::index_uni(j),
                   stan::model::index_uni(k),
                   stan::model::index_min_max(1, K))),
              "assigning variable Q", stan::model::index_uni(j),
              stan::model::index_uni(k), stan::model::index_uni(k));
          }
        }
        current_statement__ = 61;
        for (int i = 1; i <= N; ++i) {
          current_statement__ = 37;
          stan::model::assign(P,
            stan::math::matrix_exp(
              stan::math::multiply(
                stan::model::rvalue(Q, "Q",
                  stan::model::index_uni(
                    stan::model::rvalue(covind, "covind",
                      stan::model::index_uni(i))), stan::model::index_omni(),
                  stan::model::index_omni()),
                stan::model::rvalue(timelag, "timelag",
                  stan::model::index_uni(i)))), "assigning variable P");
          current_statement__ = 38;
          stan::model::assign(probs,
            validate_probs(
              stan::math::to_vector(
                stan::model::rvalue(P, "P",
                  stan::model::index_uni(
                    stan::model::rvalue(fromstate, "fromstate",
                      stan::model::index_uni(i))), stan::model::index_omni())),
              pstream__), "assigning variable probs");
          current_statement__ = 39;
          stan::math::validate_non_negative_index("nz",
            "nzilen[fromstate[i]]",
            stan::model::rvalue(nzilen, "nzilen",
              stan::model::index_uni(
                stan::model::rvalue(fromstate, "fromstate",
                  stan::model::index_uni(i)))));
          std::vector<int> nz =
            std::vector<int>(stan::model::rvalue(nzilen, "nzilen",
                               stan::model::index_uni(
                                 stan::model::rvalue(fromstate, "fromstate",
                                   stan::model::index_uni(i)))),
              std::numeric_limits<int>::min());
          current_statement__ = 41;
          stan::model::assign(nz,
            stan::math::segment(nzinds,
              stan::model::rvalue(nzifrom, "nzifrom",
                stan::model::index_uni(
                  stan::model::rvalue(fromstate, "fromstate",
                    stan::model::index_uni(i)))),
              stan::model::rvalue(nzilen, "nzilen",
                stan::model::index_uni(
                  stan::model::rvalue(fromstate, "fromstate",
                    stan::model::index_uni(i))))), "assigning variable nz");
          current_statement__ = 59;
          if (stan::math::logical_eq(
                stan::model::rvalue(obstype, "obstype",
                  stan::model::index_uni(i)), 1)) {
            current_statement__ = 58;
            loglik = (loglik +
              stan::math::multinomial_lpmf<false>(
                stan::model::rvalue(ntostate, "ntostate",
                  stan::model::index_uni(i), stan::model::index_multi(nz)),
                stan::model::rvalue(probs, "probs",
                  stan::model::index_multi(nz))));
          } else {
            current_statement__ = 57;
            if (stan::math::logical_eq(
                  stan::model::rvalue(obstype, "obstype",
                    stan::model::index_uni(i)), 2)) {
              current_statement__ = 49;
              for (int sym1__ = 1; sym1__ <= stan::math::size(nz); ++sym1__) {
                int k;
                current_statement__ = 49;
                k = nz[(sym1__ - 1)];
                current_statement__ = 55;
                if (stan::math::logical_gt(
                      stan::model::rvalue(ntostate, "ntostate",
                        stan::model::index_uni(i), stan::model::index_uni(k)),
                      0)) {
                  double lp = std::numeric_limits<double>::quiet_NaN();
                  current_statement__ = 50;
                  lp = (stan::model::rvalue(Q, "Q",
                          stan::model::index_uni(
                            stan::model::rvalue(covind, "covind",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(
                            stan::model::rvalue(fromstate, "fromstate",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(
                            stan::model::rvalue(fromstate, "fromstate",
                              stan::model::index_uni(i))))
                    *
                    stan::model::rvalue(timelag, "timelag",
                      stan::model::index_uni(i)));
                  current_statement__ = 52;
                  if (stan::math::logical_neq(k,
                        stan::model::rvalue(fromstate, "fromstate",
                          stan::model::index_uni(i)))) {
                    current_statement__ = 51;
                    lp = (lp +
                      stan::math::log(
                        stan::model::rvalue(Q, "Q",
                          stan::model::index_uni(
                            stan::model::rvalue(covind, "covind",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(
                            stan::model::rvalue(fromstate, "fromstate",
                              stan::model::index_uni(i))),
                          stan::model::index_uni(k))));
                  }
                  current_statement__ = 53;
                  loglik = (loglik +
                    (stan::model::rvalue(ntostate, "ntostate",
                       stan::model::index_uni(i), stan::model::index_uni(k))
                    * lp));
                }
              }
            } else {
              current_statement__ = 48;
              if (stan::math::logical_eq(
                    stan::model::rvalue(obstype, "obstype",
                      stan::model::index_uni(i)), 3)) {
                double pexactdeath = std::numeric_limits<double>::quiet_NaN();
                current_statement__ = 42;
                pexactdeath = 0;
                current_statement__ = 43;
                for (int sym1__ = 1; sym1__ <= stan::math::size(nz); ++sym1__) {
                  int k;
                  current_statement__ = 43;
                  k = nz[(sym1__ - 1)];
                  current_statement__ = 45;
                  if (stan::math::logical_neq(k,
                        stan::model::rvalue(exactdeath_state,
                          "exactdeath_state", stan::model::index_uni(i)))) {
                    current_statement__ = 44;
                    pexactdeath = (pexactdeath +
                      (stan::model::rvalue(probs, "probs",
                         stan::model::index_uni(k))
                      *
                      stan::model::rvalue(Q, "Q",
                        stan::model::index_uni(
                          stan::model::rvalue(covind, "covind",
                            stan::model::index_uni(i))),
                        stan::model::index_uni(k),
                        stan::model::index_uni(
                          stan::model::rvalue(exactdeath_state,
                            "exactdeath_state", stan::model::index_uni(i))))));
                  }
                }
                current_statement__ = 46;
                loglik = (loglik +
                  (stan::model::rvalue(ntostate, "ntostate",
                     stan::model::index_uni(i),
                     stan::model::index_uni(
                       stan::model::rvalue(exactdeath_state,
                         "exactdeath_state", stan::model::index_uni(i))))
                  * stan::math::log(pexactdeath)));
              }
            }
          }
        }
        current_statement__ = 72;
        if (stan::math::logical_gt(nsoj, 0)) {
          current_statement__ = 62;
          stan::math::validate_non_negative_index("Ptmp", "K", K);
          current_statement__ = 63;
          stan::math::validate_non_negative_index("Ptmp", "K", K);
          Eigen::Matrix<double,-1,-1> Ptmp =
            Eigen::Matrix<double,-1,-1>::Constant(K, K,
              std::numeric_limits<double>::quiet_NaN());
          double sprob = std::numeric_limits<double>::quiet_NaN();
          current_statement__ = 70;
          for (int i = 1; i <= nsoj; ++i) {
            current_statement__ = 66;
            stan::model::assign(Ptmp,
              stan::math::matrix_exp(
                stan::math::multiply(
                  stan::model::rvalue(Q, "Q",
                    stan::model::index_uni(
                      stan::model::rvalue(sojtlcid, "sojtlcid",
                        stan::model::index_uni(i))),
                    stan::model::index_omni(), stan::model::index_omni()),
                  stan::model::rvalue(sojtime, "sojtime",
                    stan::model::index_uni(i)))), "assigning variable Ptmp");
            current_statement__ = 67;
            sprob = stan::model::rvalue(Ptmp, "Ptmp",
                      stan::model::index_uni(
                        stan::model::rvalue(sojstate, "sojstate",
                          stan::model::index_uni(i))),
                      stan::model::index_uni(
                        stan::model::rvalue(sojstate, "sojstate",
                          stan::model::index_uni(i))));
            current_statement__ = 68;
            loglik = (loglik +
              stan::math::binomial_lpmf<false>(
                stan::model::rvalue(sojy, "sojy", stan::model::index_uni(i)),
                stan::model::rvalue(sojn, "sojn", stan::model::index_uni(i)),
                sprob));
          }
        }
      }
      if (emit_transformed_parameters__) {
        out__.write(loglik);
        out__.write(prior_logq);
        out__.write(prior_loghr);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> logq =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nqpars, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(logq,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nqpars),
        "assigning variable logq");
      out__.write(logq);
      Eigen::Matrix<local_scalar_t__,-1,1> loghr =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nx, DUMMY_VAR__);
      current_statement__ = 2;
      stan::model::assign(loghr,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(nx),
        "assigning variable loghr");
      out__.write(loghr);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "logq", "double",
        std::vector<size_t>{static_cast<size_t>(nqpars)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "loghr", "double",
        std::vector<size_t>{static_cast<size_t>(nx)});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> logq =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nqpars, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> logq_flat__;
        current_statement__ = 1;
        logq_flat__ = context__.vals_r("logq");
        current_statement__ = 1;
        pos__ = 1;
        current_statement__ = 1;
        for (int sym1__ = 1; sym1__ <= nqpars; ++sym1__) {
          current_statement__ = 1;
          stan::model::assign(logq, logq_flat__[(pos__ - 1)],
            "assigning variable logq", stan::model::index_uni(sym1__));
          current_statement__ = 1;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(logq);
      Eigen::Matrix<local_scalar_t__,-1,1> loghr =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(nx, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> loghr_flat__;
        current_statement__ = 2;
        loghr_flat__ = context__.vals_r("loghr");
        current_statement__ = 2;
        pos__ = 1;
        current_statement__ = 2;
        for (int sym1__ = 1; sym1__ <= nx; ++sym1__) {
          current_statement__ = 2;
          stan::model::assign(loghr, loghr_flat__[(pos__ - 1)],
            "assigning variable loghr", stan::model::index_uni(sym1__));
          current_statement__ = 2;
          pos__ = (pos__ + 1);
        }
      }
      out__.write(loghr);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"logq", "loghr"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"loglik", "prior_logq", "prior_loghr"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(
                                                                    nqpars)},
                std::vector<size_t>{static_cast<size_t>(nx)}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{},
             std::vector<size_t>{static_cast<size_t>(nqpars)},
             std::vector<size_t>{static_cast<size_t>(nx)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nqpars; ++sym1__) {
      param_names__.emplace_back(std::string() + "logq" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nx; ++sym1__) {
      param_names__.emplace_back(std::string() + "loghr" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "loglik");
      for (int sym1__ = 1; sym1__ <= nqpars; ++sym1__) {
        param_names__.emplace_back(std::string() + "prior_logq" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nx; ++sym1__) {
        param_names__.emplace_back(std::string() + "prior_loghr" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= nqpars; ++sym1__) {
      param_names__.emplace_back(std::string() + "logq" + '.' +
        std::to_string(sym1__));
    }
    for (int sym1__ = 1; sym1__ <= nx; ++sym1__) {
      param_names__.emplace_back(std::string() + "loghr" + '.' +
        std::to_string(sym1__));
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "loglik");
      for (int sym1__ = 1; sym1__ <= nqpars; ++sym1__) {
        param_names__.emplace_back(std::string() + "prior_logq" + '.' +
          std::to_string(sym1__));
      }
      for (int sym1__ = 1; sym1__ <= nx; ++sym1__) {
        param_names__.emplace_back(std::string() + "prior_loghr" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {}
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"logq\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nqpars) + "},\"block\":\"parameters\"},{\"name\":\"loghr\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nx) + "},\"block\":\"parameters\"},{\"name\":\"loglik\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_logq\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nqpars) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"prior_loghr\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nx) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"logq\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nqpars) + "},\"block\":\"parameters\"},{\"name\":\"loghr\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(nx) + "},\"block\":\"parameters\"},{\"name\":\"loglik\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"prior_logq\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nqpars) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"},{\"name\":\"prior_loghr\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(nx) + ",\"element_type\":{\"name\":\"real\"}},\"block\":\"transformed_parameters\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (nqpars + nx);
    const size_t num_transformed = emit_transformed_parameters * (((1 +
      nqpars) + nx));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (nqpars + nx);
    const size_t num_transformed = emit_transformed_parameters * (((1 +
      nqpars) + nx));
    const size_t num_gen_quantities = emit_generated_quantities * (0);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_msm_namespace::model_msm;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_msm_namespace::profiles__;
}
#endif
#endif
